config/routes.rb
Rails.application.routes.draw do
  resources :contracts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contract.rb
class Contract < ApplicationRecord
  audited comment_required: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: [:show, :edit, :update, :destroy]

  # GET /contracts
  # GET /contracts.json
  def index
    @contracts = Contract.all
  end

  # GET /contracts/1
  # GET /contracts/1.json
  def show
  end

  # GET /contracts/new
  def new
    @contract = Contract.new
  end

  # GET /contracts/1/edit
  def edit
  end

  # POST /contracts
  # POST /contracts.json
  def create
    @contract = Contract.new(contract_params)

    respond_to do |format|
      if @contract.save
        format.html { redirect_to @contract, notice: 'Contract was successfully created.' }
        format.json { render :show, status: :created, location: @contract }
      else
        format.html { render :new }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contracts/1
  # PATCH/PUT /contracts/1.json
  def update
    respond_to do |format|
      if @contract.update(contract_params)
        format.html { redirect_to @contract, notice: 'Contract was successfully updated.' }
        format.json { render :show, status: :ok, location: @contract }
      else
        format.html { render :edit }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contracts/1
  # DELETE /contracts/1.json
  def destroy
    @contract.destroy
    respond_to do |format|
      format.html { redirect_to contracts_url, notice: 'Contract was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contract
      @contract = Contract.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contract_params
      params.require(:contract).permit(:loan_number, :state, :contract_type, :source)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_form.html.erb
<%= form_with(model: contract, local: true) do |form| %>
  <% if contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contract.errors.count, "error") %> prohibited this contract from being saved:</h2>

      <ul>
      <% contract.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :loan_number %>
    <%= form.text_field :loan_number, id: :contract_loan_number %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :contract_state %>
  </div>

  <div class="field">
    <%= form.label :contract_type %>
    <%= form.text_field :contract_type, id: :contract_contract_type %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source, id: :contract_source %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contracts/edit.html.erb
<h1>Editing Contract</h1>

<%= render 'form', contract: @contract %>

<%= link_to 'Show', @contract %> |
<%= link_to 'Back', contracts_path %>

app/views/contracts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contracts</h1>

<table>
  <thead>
    <tr>
      <th>Loan number</th>
      <th>State</th>
      <th>Contract type</th>
      <th>Source</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contracts.each do |contract| %>
      <tr>
        <td><%= contract.loan_number %></td>
        <td><%= contract.state %></td>
        <td><%= contract.contract_type %></td>
        <td><%= contract.source %></td>
        <td><%= link_to 'Show', contract %></td>
        <td><%= link_to 'Edit', edit_contract_path(contract) %></td>
        <td><%= link_to 'Destroy', contract, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contract', new_contract_path %>

app/views/contracts/new.html.erb
<h1>New Contract</h1>

<%= render 'form', contract: @contract %>

<%= link_to 'Back', contracts_path %>

app/views/contracts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Loan number:</strong>
  <%= @contract.loan_number %>
</p>

<p>
  <strong>State:</strong>
  <%= @contract.state %>
</p>

<p>
  <strong>Contract type:</strong>
  <%= @contract.contract_type %>
</p>

<p>
  <strong>Source:</strong>
  <%= @contract.source %>
</p>

<%= link_to 'Edit', edit_contract_path(@contract) %> |
<%= link_to 'Back', contracts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PocAudited</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>